arch:
  # - arm64
  - amd64
language: minimal
sudo: required
before_install:
  - curl -fsSL https://raw.githubusercontent.com/zeduperes/ci-setup-docker-buildx/master/setup.sh | bash
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./build.sh "$TARGET" "$GIT_TAG" -p
