name: GitHub Actions CI

on:
  push:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  buildx:
    strategy:
      fail-fast: false
      matrix:
        target:
          # - agent2-alpine
          - agent-alpine
         # - agent-centos
         # - agent-ubuntu
         # - java-gateway-alpine
         # - java-gateway-centos
         # - java-gateway-ubuntu
         # - proxy-mysql-alpine
         # - proxy-mysql-centos
         # - proxy-mysql-ubuntu
         # - proxy-sqlite3-alpine
         # - proxy-sqlite3-centos
         # - proxy-sqlite3-ubuntu
         # - server-mysql-alpine
         # - server-mysql-centos
         # - server-mysql-ubuntu
         # - server-pgsql-alpine
         # - server-pgsql-centos
         # - server-pgsql-ubuntu
         # - snmptraps-alpine
         # - snmptraps-centos
         # - snmptraps-ubuntu
         # - web-apache-mysql-alpine
         # - web-apache-mysql-centos
         # - web-apache-mysql-ubuntu
         # - web-apache-pgsql-alpine
         # - web-apache-pgsql-centos
         # - web-apache-pgsql-ubuntu
         # - web-nginx-mysql-alpine
         # - web-nginx-mysql-centos
         # - web-nginx-mysql-ubuntu
         # - web-nginx-pgsql-alpine
         # - web-nginx-pgsql-centos
         # - web-nginx-pgsql-ubuntu
         # - zabbix-appliance-rhel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ${{ matrix.target }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          curl -fsSL https://raw.githubusercontent.com/zeduperes/ci-setup-docker-buildx/master/setup.sh | bash
          ./build-all-tags.sh ${{ matrix.target }} -p
